// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3VFpaqnPH3mXTYx2y3QNNYAfND1EKRxE',
    appId: '1:863755640811:web:14b953034c410bdf5003ae',
    messagingSenderId: '863755640811',
    projectId: 'contavida-535f9',
    authDomain: 'contavida-535f9.firebaseapp.com',
    storageBucket: 'contavida-535f9.firebasestorage.app',
    measurementId: 'G-K0XRJG8WJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4ht0IVBb__nWuDYMw-L6XGPnD_1LOu3U',
    appId: '1:863755640811:android:e3ef3b8ad970c5bf5003ae',
    messagingSenderId: '863755640811',
    projectId: 'contavida-535f9',
    storageBucket: 'contavida-535f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA15pJV2p_KhwbmW4fuFQzfAXB74uxxZ7M',
    appId: '1:863755640811:ios:e75e5eeca44f7ca35003ae',
    messagingSenderId: '863755640811',
    projectId: 'contavida-535f9',
    storageBucket: 'contavida-535f9.firebasestorage.app',
    iosBundleId: 'com.example.contavida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA15pJV2p_KhwbmW4fuFQzfAXB74uxxZ7M',
    appId: '1:863755640811:ios:e75e5eeca44f7ca35003ae',
    messagingSenderId: '863755640811',
    projectId: 'contavida-535f9',
    storageBucket: 'contavida-535f9.firebasestorage.app',
    iosBundleId: 'com.example.contavida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3VFpaqnPH3mXTYx2y3QNNYAfND1EKRxE',
    appId: '1:863755640811:web:e368aa3c133109725003ae',
    messagingSenderId: '863755640811',
    projectId: 'contavida-535f9',
    authDomain: 'contavida-535f9.firebaseapp.com',
    storageBucket: 'contavida-535f9.firebasestorage.app',
    measurementId: 'G-07VKVJT626',
  );
}
